---
- hosts: databases
  user: vagrant
  sudo: yes
  vars:
   - mediawikiIP: "{{ hostvars['mediawiki.example.com']['ansible_eth1']['ipv4']['address'] }}"
   - replUS: replicator
   - replPW: ciaociao 
   - rootMY: root
   - rootMYpw: ehiehi
  roles:
   - mysql

#- hosts: db2.example.com
#  user: vagrant
#  sudo: yes
#  vars:
#   - mediawikiIP: "{{ hostvars['mediawiki.example.com']['ansible_eth1']['ipv4']['address'] }}"
#   - replUS: replicator
#   - replPW: ciao
#  roles:
#   - mysql
