---
# the role replica will be run twice, with the master-slave relationship inverted to make master-master replication
- hosts: db1.example.com
  user: vagrant
  sudo: yes
  vars:
   - slaveIP: "{{ hostvars['db1.example.com']['ansible_eth1']['ipv4']['address'] }}"
   - slave: db1.example.com
   - masterIP: "{{ hostvars['db2.example.com']['ansible_eth1']['ipv4']['address'] }}"
   - master: db2.example.com
   - replUS: replicator
   - replPW: ciaociao
   - rootMY: root
   - rootMYpw: ehiehi
  roles:
   - replication

- hosts: db2.example.com
  user: vagrant
  sudo: yes
  vars:
   - masterIP: "{{ hostvars['db1.example.com']['ansible_eth1']['ipv4']['address'] }}"
   - master: db1.example.com
   - slaveIP: "{{ hostvars['db2.example.com']['ansible_eth1']['ipv4']['address'] }}"
   - slave: db2.example.com
   - replUS: replicator
   - replPW: ciaociao
   - rootMY: root
   - rootMYpw: ehiehi
  roles:
   - replication

