---
- name: Install MySql
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
   - mysql-server
   - mysql-client
  register: MySqlinstalled

- name: Install python-MysqlDB
  apt: pkg=python-mysqldb state=installed update_cache=true

- name: set mysql root passwd
  mysql_user: name=root password=ciao state=present

- name: make root PW idempotent
  template: src=roles/mysql/templates/.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  
- name: allow IP von Mediaserver to MySql
  mysql_user: login_user=root login_password=ciao user=root host={{ mediawikiIP }} password=ciao priv=*.*:ALL state=present

- name: copy mysql configuration
  template: src=roles/mysql/templates/my1.cnf dest=/etc/mysql/my.cnf force=yes mode=0644
  register: MySqlDONE
  notify:
   - Restart Mysql

- name: Create Replicator user
  mysql_user: name=replicator password=ciao host=% priv="*.*:REPLICATION SLAVE" state=present
  notify:
   - Restart Mysql

